version: 2.1

## adding an anchor for the docker image
docker_default_img: &default_img
    docker:
        - image: circleci/node:13.8.0

jobs:
    say_hello_world:
        <<: *default_img
        steps:
            - run:
                  name: Say Hello World
                  command: echo "Hello World from Mina"

workflows:
    hello_world_workflow:
        jobs:
            - say_hello_world
