version: 2.1

## adding an anchor for the docker image
docker_default_img: &default_img
    docker:
        - image: circleci/node:13.8.0

jobs:

    build:
        <<: *default_img
        steps:
            ## checks out the code at the repo
            - checkout
            ## downloads and installs npm and the required dependencies
            - run: npm i
            ## saving the downloaded files to save the bandwidth later
            - save_cache:
                paths: [/src/node_modules]
                key: npm_packages
            ## the linting step
            - run: npm run lint

    test:
        <<: *default_img
        steps:
            ## checks out the code at the repo
            - checkout
            ## restoring the cache to save the bandwidth
            - restore_cache:
                keys: [npm_packages]
            ## installing the package and the required dependencies from the cache
            - run: npm i
            ## the linting step
            - run: npm run test

    analyze:
        <<: *default_img
        steps:
          - run: npm audit
          - run:
                name: Run on Failure
                command: echo "A job has failed and this step was run for this reason"
                when: on_fail


workflows:

    build_test_analyze:
        jobs:
            - build
            - test:
                requires: [build]
            - analyze:
                requires: [test]
